services:
  server:
    build: ./app
    volumes:
      - ./app:/app
      - ./gcp-credentials:/credentials:ro  # Simple read-only mount
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcp-key.json
      - NUM_ROUNDS=${NUM_ROUNDS:-1}
      - SERVER_ADDRESS=0.0.0.0:8080

    command: ["python", "server.py"]
    ports:
      - "8080:8080"

  client1:
    build: ./app
    volumes:
      - ./app:/app
      - ./gcp-credentials:/credentials:ro
    environment:
      - BANK_ID=1
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcp-key.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOAML_PREFIX=${GOAML_PREFIX}
      - GOAML_LIMIT=${GOAML_LIMIT}
      - SERVER_ADDRESS=server:8080

    command: ["python", "client.py"]
    depends_on:
      - server

  client2:
    build: ./app
    volumes:
      - ./app:/app
      - ./gcp-credentials:/credentials:ro
    environment:
      - BANK_ID=2
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcp-key.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOAML_PREFIX=${GOAML_PREFIX}
      - GOAML_LIMIT=${GOAML_LIMIT}
      - SERVER_ADDRESS=server:8080
    command: ["python", "client.py"]
    depends_on:
      - server

  client3:
    build: ./app
    volumes:
      - ./app:/app
      - ./gcp-credentials:/credentials:ro
    environment:
      - BANK_ID=3
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcp-key.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOAML_PREFIX=${GOAML_PREFIX}
      - GOAML_LIMIT=${GOAML_LIMIT}
      - SERVER_ADDRESS=server:8080
    command: ["python", "client.py"]
    depends_on:
      - server

  client4:
    build: ./app
    volumes:
      - ./app:/app
      - ./gcp-credentials:/credentials:ro
    environment:
      - BANK_ID=4
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcp-key.json
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOAML_PREFIX=${GOAML_PREFIX}
      - GOAML_LIMIT=${GOAML_LIMIT}
      - SERVER_ADDRESS=server:8080
    command: ["python", "client.py"]
    depends_on:
      - server